### ISSUE TITLE
Create basic `README` with project specification

### ISSUE THREAD

**Issue by yurixander** [snappy-turtle/img-sharing-webapp#22]
The idea is to have the project's description and workflow defined in a more formal manner.

For example, we will need:
* [ ] an introduction section on the `README` file, which outlines the high-level idea and description of the project,
* [ ] an Authors section with our names and GitHub profile links,
* [ ] a tech stack section where the different technologies, programming languages, and libraries are outlined and their purposes are clarified
* [ ] goals and progress section, outlining the milestones and their due dates
